//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatbot._42Maru.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chatbot._42Maru.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   카테고리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 액티비티가 실패한 경우에도 자동화에서 액티비티를 계속 실행합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue on error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Carousel 데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendCarousel_Carousel_Description {
            get {
                return ResourceManager.GetString("SendCarousel_Carousel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Carousel 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendCarousel_Carousel_DisplayName {
            get {
                return ResourceManager.GetString("SendCarousel_Carousel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Carousel 타입의 응답 메세지 전달과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendCarousel_Description {
            get {
                return ResourceManager.GetString("SendCarousel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Carousel Reply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendCarousel_DisplayName {
            get {
                return ResourceManager.GetString("SendCarousel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media 타입의 응답 메세지 전달 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendMedia_Description {
            get {
                return ResourceManager.GetString("SendMedia_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Media Reply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendMedia_DisplayName {
            get {
                return ResourceManager.GetString("SendMedia_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media 데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendMedia_Media_Description {
            get {
                return ResourceManager.GetString("SendMedia_Media_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media 데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendMedia_Media_DisplayName {
            get {
                return ResourceManager.GetString("SendMedia_Media_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text 타입이 응답 메세지 전달과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_Description {
            get {
                return ResourceManager.GetString("SendText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Text Reply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_DisplayName {
            get {
                return ResourceManager.GetString("SendText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   42Maru 챗봇의 엔드포인트 정보, 형식은 http(s)://hostname:port 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_Endpoint_Description {
            get {
                return ResourceManager.GetString("SendText_Endpoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   42Maru 엔드포인트 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_Endpoint_DisplayName {
            get {
                return ResourceManager.GetString("SendText_Endpoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전송 결과로 성공시 true 실패시 false 입니다. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_Result_Description {
            get {
                return ResourceManager.GetString("SendText_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전송 결과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_Result_DisplayName {
            get {
                return ResourceManager.GetString("SendText_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시나리오 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_ScenarioId_Description {
            get {
                return ResourceManager.GetString("SendText_ScenarioId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시나리오 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_ScenarioId_DisplayName {
            get {
                return ResourceManager.GetString("SendText_ScenarioId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대화의 세션 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_SessionId_Description {
            get {
                return ResourceManager.GetString("SendText_SessionId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대화의 세션 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_SessionId_DisplayName {
            get {
                return ResourceManager.GetString("SendText_SessionId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text 데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_Text_Description {
            get {
                return ResourceManager.GetString("SendText_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text 데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SendText_Text_DisplayName {
            get {
                return ResourceManager.GetString("SendText_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류를 발생되기 전까지 동작에서 기다리는 시간 초단위. 기본은 60초입니다. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   액티비티 최대 수행시간을 초과했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}값은 명시적으로 지정되어야 합니다. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
